In [1]:
import pandas as pd
df = pd.read_excel("../../data/BASE_DATOS_VIVEROS_MAYO_2026.xlsx")
df.head()

,No.,DEPARTAMENTO,MUNICIPIO,VEREDA,NOMBRE DEL VIVERO,LATITUD,LONGITUD,ALTITUD,ESTADO,NÚMERO DE REGISTRO OTORGADO,...,PROPIETARIO NOMBRE,NO. CEDULA DEL PROPIETARIO,TELÉFONO DEL PROPIETARIO,DIRECCIÓN DEL PROPIETARIO,CORREO ELECTRÓNICO,NOMBRE DEL ASISTENTE TÉCNICO,CÉDULA DEL ASISTENTE TÉCNICO,TARJETA PROFESIONAL DEL ASISTENTE TÉCNICO,TELÉFONO DEL ASISTENTE TÉCNICO,OBSERVACIONES
0,1,AMAZONAS,LETICIA,SECTOR NAZARETH,VIVERO GRANJA NAZARETH,-4.106478,-70.037956,71,REGISTRADO,910010001,...,OSCAR ENRIQUE SÁNCHEZ GUERRERO,"15,879,024",3187912285,CALLE 11 # 12-98 BARRIO VICTORIA REGIA,agricultura@amazonas.gov.co,MAYRA ALEJANDRA ROJAS VARON,1110518462,161016-0568965 TLM,3113448291,NaN
1,1,ANTIOQUIA,Jerico,La Estrella,San Basilio S.A.S,5.758195,-75.768022,2800,Registrado,92950,...,Duban Alberto Ruiz Ospina,70730011,3155750451,Calle cuarta # 2-25 Barrio San Vivente Jericó,gerencia@productorasanbasilio.com; asistenciat...,Edilma Betancurt Ruiz,24791263,66209436973RIS,3105187628,NaN
2,2,ANTIOQUIA,Jerico,El Balcon Sector La Leona,El Balcon,5.809731,-75.765759,1900,Registrado,92948,...,Jose Maria Prieto Villegas,71591849,3128512959,Carrera 76 # 34a-41 Oficina 102 Edificio Camburo,josemariaprieto@gmail.com,Catalina Maria Zuluaga Amaya,43873262,,,NaN
3,3,ANTIOQUIA,Entrerrios,El Zancudo - paraje La Tabla- Via San Pedro - ...,Agricolas y Vivero Guacamayas,6.561369,-75.537789,2502,Registrado,92946,...,Juan Camilo Ruiz Perez,15315744,3104363299,Calle9# 31 - 105 El Poblado,juancamilorp@gmail.com,Lina Marcela Morales Herrera,1040037431,53639,3213988643,NaN
4,4,ANTIOQUIA,Urrao,San Jose - Via Urrao - Betulia Km 7,Plantuladora El Paraiso,6.259529,-76.129879,1876,Registrado,22666,...,Julian Andres Bulla,1055670236,3124521042,Marinilla - Cra 44-B #2915 Conjunto Bariloche,"plantulasparaiso3@hotmail,com",Diego Armando Solano Montenegro,74282972,23935,3104932787,NaN

In [2]:
df.shape

(11295, 30)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11295 entries, 0 to 11294
Data columns (total 30 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   No.                                         2640 non-null   object
 1   DEPARTAMENTO                                2639 non-null   str
 2   MUNICIPIO                                   2641 non-null   str
 3   VEREDA                                      2608 non-null   str
 4   NOMBRE DEL VIVERO                           2647 non-null   str
 5   LATITUD                                     2485 non-null   object
 6   LONGITUD                                    2485 non-null   object
 7   ALTITUD                                     2285 non-null   object
 8   ESTADO                                      2629 non-null   str
 9   NÚMERO DE REGISTRO OTORGADO                 2532 non-null   object
 10  FECHA DE OTORGAMIENTO DE REGISTRO           2495 non-null   object
 11  VIGENCIA                                    2380 non-null   object
 12  CAPACIDAD DE PRODUCCIÓN plantas/año         1965 non-null   object
 13  FRUTALES                                    1774 non-null   object
 14  CITRICOS                                    720 non-null    object
 15  FORESTALES                                  2956 non-null   object
 16  ORNAMENTALES                                7811 non-null   object
 17  HORTALIZAS                                  332 non-null    object
 18  AROMATICAS Y MEDICINALES                    811 non-null    object
 19  OTRAS ESPECIES                              1132 non-null   object
 20  PROPIETARIO NOMBRE                          2610 non-null   str
 21  NO. CEDULA DEL PROPIETARIO                  2556 non-null   object
 22  TELÉFONO DEL PROPIETARIO                    2591 non-null   object
 23  DIRECCIÓN DEL PROPIETARIO                   2624 non-null   object
 24  CORREO ELECTRÓNICO                          2470 non-null   object
 25  NOMBRE DEL ASISTENTE TÉCNICO                2237 non-null   object
 26  CÉDULA  DEL ASISTENTE TÉCNICO               2174 non-null   object
 27  TARJETA PROFESIONAL  DEL ASISTENTE TÉCNICO  2154 non-null   object
 28  TELÉFONO DEL ASISTENTE TÉCNICO              1851 non-null   object
 29  OBSERVACIONES                               942 non-null    object
dtypes: object(24), str(6)
memory usage: 2.6+ MB

In [4]:
df.describe()

,No.,DEPARTAMENTO,MUNICIPIO,VEREDA,NOMBRE DEL VIVERO,LATITUD,LONGITUD,ALTITUD,ESTADO,NÚMERO DE REGISTRO OTORGADO,...,PROPIETARIO NOMBRE,NO. CEDULA DEL PROPIETARIO,TELÉFONO DEL PROPIETARIO,DIRECCIÓN DEL PROPIETARIO,CORREO ELECTRÓNICO,NOMBRE DEL ASISTENTE TÉCNICO,CÉDULA DEL ASISTENTE TÉCNICO,TARJETA PROFESIONAL DEL ASISTENTE TÉCNICO,TELÉFONO DEL ASISTENTE TÉCNICO,OBSERVACIONES
count,2640,2639,2641,2608,2647,2485,2485,2285,2629,2532,...,2610,2556,2591,2624,2470,2237,2174,2154,1851,942
unique,364,44,680,2022,2415,2243,2243,1257,37,2446,...,2310,2196,2255,2257,2112,1419,1243,1328,987,307
top,1,CUNDINAMARCA,FUSAGASUGÁ,CHINAUTA,LA ESPERANZA,0,0,0,REGISTRADO,50001-217,...,PROYECTO REDD+ CUENCA ALTO BAUDÓ,42879010,3134261781,VIVERO,NO TIENE,ROSAURA BAQUERO RAMIREZ,40384728,9439,0,ACTIVO
freq,32,364,102,51,6,69,69,75,2017,5,...,11,11,11,21,25,46,46,43,98,309

In [5]:
df.dtypes

No.                                           object
DEPARTAMENTO                                     str
MUNICIPIO                                        str
VEREDA                                           str
NOMBRE DEL VIVERO                                str
LATITUD                                       object
LONGITUD                                      object
ALTITUD                                       object
ESTADO                                           str
NÚMERO DE REGISTRO OTORGADO                   object
FECHA DE OTORGAMIENTO DE REGISTRO             object
VIGENCIA                                      object
CAPACIDAD DE PRODUCCIÓN plantas/año           object
FRUTALES                                      object
CITRICOS                                      object
FORESTALES                                    object
ORNAMENTALES                                  object
HORTALIZAS                                    object
AROMATICAS Y MEDICINALES                      object
OTRAS ESPECIES                                object
PROPIETARIO NOMBRE                               str
NO. CEDULA DEL PROPIETARIO                    object
TELÉFONO DEL PROPIETARIO                      object
DIRECCIÓN DEL PROPIETARIO                     object
CORREO ELECTRÓNICO                            object
NOMBRE DEL ASISTENTE TÉCNICO                  object
CÉDULA  DEL ASISTENTE TÉCNICO                 object
TARJETA PROFESIONAL  DEL ASISTENTE TÉCNICO    object
TELÉFONO DEL ASISTENTE TÉCNICO                object
OBSERVACIONES                                 object
dtype: object

In [6]:
df.isna()

,No.,DEPARTAMENTO,MUNICIPIO,VEREDA,NOMBRE DEL VIVERO,LATITUD,LONGITUD,ALTITUD,ESTADO,NÚMERO DE REGISTRO OTORGADO,...,PROPIETARIO NOMBRE,NO. CEDULA DEL PROPIETARIO,TELÉFONO DEL PROPIETARIO,DIRECCIÓN DEL PROPIETARIO,CORREO ELECTRÓNICO,NOMBRE DEL ASISTENTE TÉCNICO,CÉDULA DEL ASISTENTE TÉCNICO,TARJETA PROFESIONAL DEL ASISTENTE TÉCNICO,TELÉFONO DEL ASISTENTE TÉCNICO,OBSERVACIONES
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11290,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11291,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
11292,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
11293,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
11294,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True

In [7]:
df.isna().sum()

No.                                            8655
DEPARTAMENTO                                   8656
MUNICIPIO                                      8654
VEREDA                                         8687
NOMBRE DEL VIVERO                              8648
LATITUD                                        8810
LONGITUD                                       8810
ALTITUD                                        9010
ESTADO                                         8666
NÚMERO DE REGISTRO OTORGADO                    8763
FECHA DE OTORGAMIENTO DE REGISTRO              8800
VIGENCIA                                       8915
CAPACIDAD DE PRODUCCIÓN plantas/año            9330
FRUTALES                                       9521
CITRICOS                                      10575
FORESTALES                                     8339
ORNAMENTALES                                   3484
HORTALIZAS                                    10963
AROMATICAS Y MEDICINALES                      10484
OTRAS ESPECIES                                10163
PROPIETARIO NOMBRE                             8685
NO. CEDULA DEL PROPIETARIO                     8739
TELÉFONO DEL PROPIETARIO                       8704
DIRECCIÓN DEL PROPIETARIO                      8671
CORREO ELECTRÓNICO                             8825
NOMBRE DEL ASISTENTE TÉCNICO                   9058
CÉDULA  DEL ASISTENTE TÉCNICO                  9121
TARJETA PROFESIONAL  DEL ASISTENTE TÉCNICO     9141
TELÉFONO DEL ASISTENTE TÉCNICO                 9444
OBSERVACIONES                                 10353
dtype: int64

In [8]:
df.isnull().sum()

No.                                            8655
DEPARTAMENTO                                   8656
MUNICIPIO                                      8654
VEREDA                                         8687
NOMBRE DEL VIVERO                              8648
LATITUD                                        8810
LONGITUD                                       8810
ALTITUD                                        9010
ESTADO                                         8666
NÚMERO DE REGISTRO OTORGADO                    8763
FECHA DE OTORGAMIENTO DE REGISTRO              8800
VIGENCIA                                       8915
CAPACIDAD DE PRODUCCIÓN plantas/año            9330
FRUTALES                                       9521
CITRICOS                                      10575
FORESTALES                                     8339
ORNAMENTALES                                   3484
HORTALIZAS                                    10963
AROMATICAS Y MEDICINALES                      10484
OTRAS ESPECIES                                10163
PROPIETARIO NOMBRE                             8685
NO. CEDULA DEL PROPIETARIO                     8739
TELÉFONO DEL PROPIETARIO                       8704
DIRECCIÓN DEL PROPIETARIO                      8671
CORREO ELECTRÓNICO                             8825
NOMBRE DEL ASISTENTE TÉCNICO                   9058
CÉDULA  DEL ASISTENTE TÉCNICO                  9121
TARJETA PROFESIONAL  DEL ASISTENTE TÉCNICO     9141
TELÉFONO DEL ASISTENTE TÉCNICO                 9444
OBSERVACIONES                                 10353
dtype: int64

In [9]:
from openpyxl import load_workbook

libro = load_workbook("../../data/BASE_DATOS_VIVEROS_MAYO_2026.xlsx")

In [10]:
#libro.sheetnames devuelve una lista de cadenas de texto con los nombres de todas las pestañas (hojas) que existen dentro del archivo Excel.
print(libro.sheetnames)

#selecciona la oja del excel activa y la guarda en la variable hoja
hoja = libro.active

#hoja.merged_cells.ranges accede a una oclección interna de objetos de tipo CellRange este representa todos los bloques de celdas combinadas en la hoja seleccionada(hoja).

# el for es para recorrer todos los bloques en los que aparecen celdas combinadas , con el print(rango) se mprime en pantalla el rango exactoe n coordenadas excel donde están las celdas combinadas.
for rango in hoja.merged_cells.ranges:
    print(rango)

['BASE VIVEROS REGIST MAYO 2026']
U4354:U4403
K2512:K2545
U4451:U4459
B3143:B3174
AB8036:AB8039
AC7298:AC7299
K8707:K8742
G11106:G11109
J3834:J3837
G7310:G7321
AA2828:AA2836
T4514:T4549
M4868:M4887
U3761:U3775
I2080:I2097
W6973:W6974
Z7998:Z8001
AA2688:AA2699
AD3780:AD3789
M1437:M1469
H8209:H8210
AA4599:AA4610
Z10455:Z10584
AB7958:AB7960
S4971:S4982
W7431:W7432
W6907:W6912
C5790:C5824
B1254:B1255
F3890:F3894
G7371:G7387
A2675:A2676
J1777:J1836
G7801:G7802
A917:A923
W240:W241
O7640:O7641
F4888:F4889
L8922:L8925
D8093:D8102
W4037:W4085
M3553:M3559
G441:G442
H10974:H11061
Z459:Z461
AC5366:AC5367
AD1853:AD1882
P8222:P8223
Z8126:Z8136
D311:D312
O2019:O2022
V6929:V6930
A3940:A4003
AB3125:AB3142
S8186:S8189
F8802:F8803
B5000:B5018
B1503:B1508
Y10585:Y10633
AC7472:AC7487
H8190:H8194
B2033:B2035
J2823:J2827
Z8174:Z8178
B4027:B4036
AD8778:AD8794
R8282:R8283
M8479:M8480
H8085:H8088
D2098:D2100
V1921:V1930
V1131:V1135
N4508:N4513
O10840:O10973
E7928:E7931
V2678:V2687
C2031:C2032
Y1470:Y1471
AD3560:AD3567
AC1180:AC1181
AA8202:AA8203
B230:B231
Z1289:Z1318
S7340:S7342
X7998:X8001
E8080:E8084
T4354:T4403
J2512:J2545
A1979:A1987
U1247:U1248
T4451:T4459
Y2203:Y2242
R1669:R1675
AA8036:AA8039
X8004:X8008
E1711:E1723
J8707:J8742
AB9299:AB9367
AC11279:AC11281
U3855:U3861
I3834:I3837
AD10131:AD10284
AA9023:AA9091
B7787:B7790
E7082:E7083
G1726:G1727
S4514:S4549
A8493:A8514
L4868:L4887
X755:X788
V6973:V6974
N1509:N1527
S7024:S7026
I4936:I4966
H459:H461
AD6901:AD6902
L1853:L1882
L1437:L1469
S4820:S4821
M2994:M3001
C351:C353
L242:L246
U3876:U3881
AB8229:AB8230
A1254:A1255
D8172:D8173
G6590:G6802
M5102:M5116
E3890:E3894
K7472:K7487
M6857:M6859
S9784:S9786
G5350:G5351
G2858:G2928
Y1677:Y1707
F7801:F7802
W7324:W7328
R4412:R4413
W2713:W2720
K8922:K8925
P8751:P8758
Z8585:Z8586
F441:F442
D8683:D8684
O5079:O5093
R7388:R7399
Z8591:Z8614
U2059:U2061
F8232:F8233
R8625:R8671
B1011:B1014
U8477:U8478
N2019:N2022
U825:U828
C5828:C5930
S2386:S2417
J1622:J1638
K415:K423
H1289:H1318
AD6425:AD6428
AB7472:AB7487
R1766:R1767
P9161:P9229
E3810:E3825
Y3175:Y3187
I3733:I3757
W4723:W4737
N4696:N4722
G2203:G2242
S10286:S10441
C2098:C2100
AC8778:AC8794
U1131:U1135
L8479:L8480
U2471:U2480
P5099:P5101
J9299:J9367
P3776:P3779
AA530:AA562
K7331:K7332
I1586:I1599
K1102:K1127
AC6984:AC6986
X4550:X4569
V230:V231
K7564:K7568
B2031:B2032
A7693:A7768
K9375:K9379
AB4588:AB4598
R2546:R2642
AB1180:AB1181
Q7672:Q7673
M8860:M8876
B6995:B6996
R5932:R6034
M7973:M7975
H7618:H7626
G1331:G1339
AB4478:AB4507
AD1736:AD1742
I5466:I5784
Y7310:Y7321
K3102:K3103
H3834:H3837
Z1586:Z1599
A7787:A7790
H3253:H3292
U585:U587
P5324:P5333
W3002:W3035
M1509:M1527
Y8225:Y8226
W8762:W8765
U8940:U8952
AA2261:AA2332
B237:B238
AA7877:AA7878
L8052:L8075
W7893:W7894
J3553:J3559
N2366:N2377
W8015:W8033
R4820:R4821
C8477:C8478
E2006:E2009
G3194:G3209
T3876:T3881
Y5402:Y5444
C8172:C8173
A2386:A2417
L5102:L5116
R7924:R7927
E8237:E8238
F8904:F8908
R9784:R9786
X1677:X1707
Z7932:Z7934
Y7953:Y7954
V2713:V2720
N5079:N5093
J5146:J5233
Y8591:Y8614
A4830:A4831
E8232:E8233
AA4971:AA4982
R4349:R4353
K5790:K5824
L3352:L3359
P7961:P7962
J415:J423
AC6425:AC6428
H7310:H7321
Z7868:Z7871
M7793:M7794
V4723:V4737
S3605:S3620
Z8085:Z8088
AA878:AA890
Y1931:Y1955
AC4599:AC4610
T2471:T2480
O5099:O5101
AB8768:AB8769
X8220:X8221
Z8168:Z8171
N7885:N7886
AD3093:AD3101
W8174:W8178
Q1249:Q1250
H1586:H1599
C7907:C7910
R4830:R4831
W4550:W4569
J7331:J7332
AA10651:AA10666
AB7845:AB7848
J7564:J7568
AC7674:AC7675
G5352:G5353
C1056:C1060
J9375:J9379
O7853:O7854
P3309:P3351
A6995:A6996
S1015:S1016
AD3490:AD3502
G8225:G8226
AA2010:AA2012
V3238:V3252
I7916:I7919
G7618:G7626
AB2512:AB2545
AA7941:AA7942
K11062:K11105
T7776:T7778
N8044:N8047
E2076:E2079
X1329:X1330
C8048:C8051
U7011:U7012
F311:F312
G5402:G5444
J3102:J3103
AD7911:AD7915
C7061:C7062
S5388:S5391
V928:V950
X9368:X9374
AC7402:AC7403
O5324:O5333
H8775:H8776
T2126:T2202
V3002:V3035
K8822:K8842
V1677:V1707
Z2261:Z2332
M8235:M8236
E5828:E5930
P7899:P7903
Z7877:Z7878
K8052:K8075
C1503:C1508
E6502:E6589
W11201:W11264
V4004:V4016
L2708:L2712
F1772:F1775
H3720:H3732
H8486:H8487
O7292:O7293
O1015:O1016
K8156:K8160
H2481:H2510
E11139:E11200
D4890:D4935
AA7024:AA7026
J1331:J1339
I5146:I5233
AB1728:AB1731
V4414:V4442
R7634:R7635
AB2333:AB2356
Y7011:Y7012
N8954:N9022
G5070:G5078
M8920:M8921
R7329:R7330
V3568:V3575
Q6920:Q6921
AD3826:AD3833
AB7904:AB7906
O5932:O6034
V6907:V6912
Y7868:Y7871
Z4967:Z4970
F580:F583
L11110:L11138
H1726:H1727
V2837:V2857
Y4763:Y4764
Y8085:Y8088
G10442:G10454
Z878:Z890
X1931:X1955
N8089:N8092
N2787:N2799
T8515:T8521
S2471:S2480
AA8768:AA8769
W8220:W8221
Y8168:Y8171
D7404:D7430
B7907:B7910
AC3093:AC3101
S3046:S3092
M2243:M2260
J4936:J4966
AA7845:AA7848
I8161:I8163
R1320:R1321
U726:U727
P7849:P7852
G3890:G3894
N6922:N6923
R1015:R1016
O3309:O3351
O10634:O10650
U4017:U4026
Z2010:Z2012
H7916:H7919
AB925:AB926
O7433:O7459
J11062:J11105
AA5466:AA5784
H4983:H4991
J3473:J3489
H2858:H2928
F8806:F8820
E9230:E9298
L3116:L3124
AD3790:AD3794
V7082:V7083
S2036:S2044
U928:U950
W9368:W9374
AB7402:AB7403
AD6275:AD6424
Y7670:Y7671
G8775:G8776
U1677:U1707
L8235:L8236
D5828:D5930
J580:J583
AB3553:AB3559
M7882:M7884
E11265:E11268
U1617:U1621
S1340:S1374
AA8689:AA8696
AC3843:AC3854
V7840:V7841
D8910:D8919
B1324:B1325
U4004:U4016
N8212:N8213
D1528:D1585
AD10455:AD10584
G6984:G6986
AD2418:AD2430
U4611:U4695
AC10651:AC10666
G3720:G3732
E3376:E3382
W8190:W8194
J8156:J8160
E7796:E7798
X7301:X7302
C5363:C5364
G4763:G4764
E8076:E8079
M8797:M8801
K2464:K2465
AA240:AA241
J4888:J4889
U4414:U4442
S2026:S2030
F5070:F5078
M8954:M9022
T8222:T8223
U8195:U8197
AC2080:AC2097
T1477:T1498
S7400:S7401
H311:H312
AA7904:AA7906
F7963:F7964
R3930:R3939
W3548:W3552
I3253:I3292
V4444:V4450
U2837:U2857
V585:V587
F10442:F10454
E7371:E7387
M8089:M8092
S8515:S8521
C5377:C5385
L2243:L2260
C7404:C7430
V8282:V8283
Q1320:Q1321
A7388:A7399
O7849:O7852
E5334:E5349
V3758:V3760
K3704:K3718
J2700:J2701
A2062:A2075
Q1015:Q1016
T821:T824
P3621:P3635
AD1997:AD2003
AA925:AA926
K1899:K1920
A4832:A4834
N7951:N7952
Z5466:Z5784
V8209:V8210
C1988:C1995
D9230:D9298
M7827:M7828
T2047:T2051
W7340:W7342
I7843:I7844
X4354:X4403
R2036:R2044
T1131:T1135
C8280:C8281
R3576:R3604
T1921:T1930
N8707:N8742
J11106:J11109
D2468:D2470
E2800:E2822
Z6973:Z6974
T1617:T1621
V2006:V2009
D683:D685
AD2688:AD2699
R1340:R1374
B7595:B7615
AB7068:AB7077
T3605:T3620
O6816:O6820
X1772:X1775
AC10455:AC10584
W5363:W5364
P242:P246
Z7431:Z7432
O7304:O7305
A4514:A4549
G3872:G3875
AC1650:AC1661
AB10651:AB10666
L5350:L5351
R10634:R10650
AD7674:AD7675
X3733:X3757
D3376:D3382
D7796:D7798
I3890:I3894
D2675:D2676
D8076:D8079
W3238:W3252
Z240:Z241
Y1711:Y1723
I4888:I4889
G8093:G8102
Z4037:Z4085
R2026:R2030
V4460:V4477
S8222:S8223
Y1329:Y1330
G311:G312
Y825:Y828
B5352:B5353
V8186:V8189
M10667:M10836
V3548:V3552
U4444:U4450
E10442:E10454
M8354:M8355
E2858:E2928
G3473:G3489
AD4835:AD4867
E7340:E7342
B5377:B5385
F4354:F4403
E2033:E2035
W351:W353
I3116:I3124
E1324:E1325
Y6920:Y6921
H7928:H7931
U6216:U6274
J3704:J3718
F7895:F7898
J8486:J8487
W5932:W6034
AC7843:AC7844
J1899:J1920
Q2017:Q2018
Z7037:Z7038
C7322:C7323
M8255:M8256
P8797:P8801
O1759:O1762
W4451:W4459
V1011:V1014
R8172:R8173
M8707:M8742
AC1728:AC1731
I11106:I11109
W7670:W7671
D3044:D3045
L3834:L3837
L7674:L7675
G2708:G2712
E7787:E7790
J1726:J1727
D8493:D8514
X9787:X9996
W8195:W8197
U326:U348
Y6973:Y6974
S1617:S1621
AC2688:AC2699
O7885:O7886
T8232:T8233
O3503:O3539
R8772:R8773
O1437:O1469
O1853:O1882
AA8015:AA8033
I4027:I4036
W1772:W1775
V4820:V4821
P2994:P3001
Y7431:Y7432
T3046:T3092
U4508:U4513
O242:O246
A7890:A7891
W3733:W3757
H3890:H3894
G3490:G3502
C2675:C2676
T3210:T3237
V9784:V9786
F3253:F3292
A8215:A8216
AB10840:AB10973
N8922:N8925
H3895:H3929
Y4037:Y4085
I4983:I4991
I441:I442
R5079:R5093
K1884:K1892
X2059:X2061
I4570:I4584
I8775:I8776
X825:X828
AD3125:AD3142
C3940:C4003
P3352:P3359
U8186:U8189
F9449:F9651
T7961:T7962
L8202:L8203
M1622:M1638
W7371:W7387
U1766:U1767
S9161:S9229
F3473:F3489
F7860:F7861
Z4723:Z4737
J2203:J2242
C1669:C1675
F7818:F7819
J6046:J6215
F2098:F2100
S3776:S3779
L1586:L1599
Y230:Y231
O10131:O10284
K2828:K2836
G1056:G1060
E2031:E2032
AA1470:AA1471
T7672:T7673
E6995:E6996
V4611:V4695
D7024:D7026
G8080:G8084
V3104:V3105
A1141:A1142
N1759:N1762
V4451:V4459
K4599:K4610
A2023:A2025
Q8172:Q8173
N7804:N7805
A1956:A1962
C4971:C4982
E2333:E2356
AB7310:AB7321
C3044:C3045
I8744:I8747
W3855:W3861
I8697:I8702
K3834:K3837
AC9023:AC9091
U2929:U2983
I1726:I1727
C8493:C8514
AC3882:AC3889
D9784:D9786
X585:X587
S5324:S5333
X2126:X2202
Z3002:Z3035
P1509:P1527
X8940:X8952
H4404:H4411
AD2261:AD2332
S8232:S8233
F3645:F3703
Q8772:Q8773
O8052:O8075
J459:J461
N1437:N1469
K8591:K8614
Q7849:Q7852
Z8015:Z8033
H4027:H4036
J8126:J8136
AB1131:AB1135
U4820:U4821
O2994:O3001
N242:N246
AA373:AA381
W3876:W3881
D2386:D2417
F3490:F3502
H8237:H8238
M7472:M7487
AC7932:AC7934
B7770:B7771
Y7324:Y7328
C6039:C6041
R8751:R8758
AB8585:AB8586
A2431:A2437
I8174:I8178
M5146:M5233
W2059:W2061
G7873:G7874
U905:U915
AA9652:AA9783
T1225:T1229
F2468:F2470
U11201:U11264
U4349:U4353
B3940:B4003
O3352:O3359
I1470:I1471
U7618:U7626
S7961:S7962
M415:M423
E2700:E2701
J1289:J1318
G3810:G3825
P7793:P7794
T1340:T1374
Y4723:Y4737
F2800:F2822
U10286:U10441
P1894:P1897
Y2031:Y2032
L9299:L9367
B7640:B7641
AC530:AC562
M7331:M7332
K1586:K1599
M1102:M1127
C444:C451
X230:X231
J9380:J9448
M7564:M7568
S1744:S1754
G8744:G8747
R4832:R4834
AD4588:AD4598
R7853:R7854
S7672:S7673
L7685:L7686
D6995:D6996
J8225:J8226
I6929:I6930
B7460:B7471
Y3238:Y3252
Y3733:Y3757
C7024:C7026
AD7941:AD7942
U3104:U3105
V3143:V3174
M1322:M1323
Q8044:Q8047
E3876:E3881
D2333:D2356
AA7310:AA7321
J5402:J5444
M3102:M3103
L10974:L11061
T2929:T2983
AA9368:AA9374
C7924:C7927
R5324:R5333
K8775:K8776
W2126:W2202
Y3002:Y3035
J7953:J7954
G7324:G7328
W8940:W8952
Y351:Y353
N10667:N10836
AC7877:AC7878
N8052:N8075
Y7893:Y7894
B7388:B7399
P2366:P2377
E8477:E8478
H6502:H6589
C2386:C2417
A1262:A1264
G8237:G8238
H8904:H8908
AA10837:AA10839
AA7801:AA7802
K3720:K3732
K7868:K7871
Q7085:Q7086
Z8806:Z8820
A7770:A7771
X8093:X8102
W8161:W8163
E2471:E2480
N7810:N7812
Y4835:Y4867
H8174:H8178
L5146:L5233
O3093:O3101
B1249:B1250
E2468:E2470
Y1477:Y1498
T4349:T4353
R9999:R10130
P8920:P8921
A3106:A3108
R7961:R7962
B2546:B2642
L415:L423
T6920:T6921
W5019:W5069
O11110:O11138
X7818:X7819
X2098:X2100
AB8085:AB8088
S6861:S6862
AC878:AC890
Q8089:Q8092
AD8768:AD8769
Z8220:Z8221
A7640:A7641
P7885:P7886
P3790:P3794
J1586:J1599
AD7845:AD7848
D5388:D5391
N7402:N7403
R1744:R1754
U1320:U1321
F8744:F8747
S7849:S7852
F1650:F1661
Q7853:Q7854
R3309:R3351
F7888:F7889
H6929:H6930
AC2010:AC2012
K7916:K7919
A7899:A7903
M11062:M11105
F8762:F8765
R7951:R7952
O7472:O7487
L1322:L1323
C2101:C2125
E8048:E8051
I5402:I5444
Y7082:Y7083
E7061:E7062
S2045:S2046
V2036:V2044
X928:X950
Z9368:Z9374
B7924:B7927
L1997:L2003
H3125:H3142
Z1503:Z1508
I7953:I7954
O8235:O8236
G5828:G5930
O8080:O8084
Z4027:Z4036
I1956:I1962
V1766:V1767
H11265:H11268
G1247:G1248
G6502:G6589
O1837:O1850
Y7840:Y7841
Q8212:Q8213
J8004:J8008
G1528:G1585
N9299:N9367
I4133:I4348
Z7801:Z7802
X4611:X4695
J3720:J3732
J7868:J7871
B2678:B2687
D3930:D3939
Q5377:Q5385
W8617:W8622
M8156:M8160
H3376:H3382
J4763:J4764
H8076:H8079
I1931:I1955
J755:J788
M7810:M7812
J8168:J8171
L4992:L4999
N3093:N3101
N2464:N2465
B4830:B4831
AC1711:AC1723
A1249:A1250
L7845:L7848
T7634:T7635
R436:R439
AA7011:AA7012
P8954:P9022
M5117:M5145
Z4460:Z4477
J10651:J10666
C1015:C1016
I11279:I11281
K2010:K2012
N8229:N8230
J4585:J4587
V2929:V2983
T6436:T6501
Z3548:Z3552
W7818:W7819
X2837:X2857
E9784:E9786
W2098:W2100
Y585:Y587
I10442:I10454
Q8354:Q8355
AB878:AB890
U1099:U1101
P8089:P8092
F5377:F5385
O2243:O2260
O3790:O3794
AA351:AA353
T1320:T1321
Y1254:Y1255
D7388:D7399
AB5094:AB5098
R7849:R7852
B7431:B7432
I1324:I1325
H5334:H5349
E7888:E7889
N2378:N2385
V462:V465
S3621:S3635
AD7801:AD7802
AD925:AD926
Q7433:Q7459
E8762:E8765
AA8093:AA8102
Q7951:Q7952
J4983:J4991
J2858:J2928
Y8209:Y8210
V3360:V3375
F3605:F3620
V1225:V1229
F4004:F4016
U1102:U1127
U2036:U2044
F8280:F8281
U3576:U3604
AA5828:AA5930
AA7670:AA7671
G2468:G2470
Y1503:Y1508
A961:A962
R917:R923
O3560:O3567
G7860:G7861
Y2033:Y2035
H2800:H2822
AD3553:AD3559
N415:N423
W1617:W1621
F4414:F4442
A8885:A8900
AC8689:AC8696
U1340:U1374
J3042:J3043
L8040:L8043
X7840:X7841
AB7928:AB7931
R6816:R6820
P8212:P8213
B7873:B7874
M9299:M9367
H4133:H4348
L7904:L7906
F6907:F6912
W4611:W4695
A2678:A2687
S7770:S7771
J4967:J4970
C3930:C3939
Y8190:Y8194
G585:G587
V8227:V8228
A2984:A2993
K8225:K8226
O7804:O7805
K4992:K4999
Y8232:Y8233
Z3238:Z3252
Z3540:Z3547
AB1711:AB1723
AC240:AC241
E726:E727
C4508:C4513
B1756:B1758
Y4460:Y4477
G3758:G3760
J7343:J7369
H11279:H11281
AB1329:AB1330
J311:J312
F9023:F9091
I4585:I4587
P10667:P10836
Y3548:Y3552
AA2512:AA2545
H10442:H10454
C8762:C8765
P8354:P8355
C4765:C4819
O8089:O8092
G7877:G7878
N2243:N2260
W1056:W1060
Z351:Z353
S1320:S1321
X1254:X1255
C7388:C7399
AA5094:AA5098
H1324:H1325
S1756:S1758
AD6590:AD6802
G5334:G5349
AC7685:AC7686
M3704:M3718
S10131:S10284
C2062:C2075
I7895:I7898
V3838:V3842
R3621:R3635
O1412:O1431
J9787:J9996
AC925:AC926
K3376:K3382
D1677:D1707
T2017:T2018
V7820:V7822
X8209:X8210
C1340:C1374
AA8683:AA8684
F7322:F7323
E3605:E3620
R3780:R3789
E8585:E8586
T3293:T3306
Y1011:Y1014
AD3102:AD3103
Z4451:Z4459
O4599:O4610
U8172:U8173
N10455:N10584
A5099:A5101
G4971:G4982
T3576:T3604
Z7670:Z7671
G3044:G3045
O3834:O3837
O7674:O7675
Z1477:Z1498
I6425:I6428
G2800:G2822
P3307:P3308
D11139:D11200
P2431:P2437
AB6973:AB6974
X326:X348
H3540:H3547
Y6502:Y6589
V1617:V1621
F683:F685
A3553:A3559
F7776:F7778
M8048:M8051
Q6816:Q6820
R1853:R1882
M4822:M4829
Z1772:Z1775
N8126:N8136
S4832:S4834
AA7796:AA7798
R242:R246
AB7431:AB7432
Q7304:Q7305
P3125:P3142
D7890:D7891
R7770:R7771
G4588:G4598
G2062:G2075
V1381:V1403
Z3733:Z3757
U8227:U8228
J3490:J3502
W3143:W3174
AD1331:AD1339
H3002:H3035
R4086:R4132
E8137:E8155
K3895:K3929
T5296:T5323
V386:V413
L4983:L4991
B4508:B4513
A1756:A1758
X4460:X4477
N1884:N1892
AA2059:AA2061
L4570:L4584
AA1329:AA1330
X1225:X1229
AA825:AA828
P11106:P11109
F7061:F7062
M1470:M1471
X8186:X8189
Y7618:Y7626
N8877:N8884
O8202:O8203
B8762:B8765
O8354:O8355
F2261:F2332
X1766:X1767
G7340:G7342
F7877:F7878
H4354:H4403
I7860:I7861
H4451:H4459
M2203:M2242
AB2006:AB2009
Z5094:Z5098
S6042:S6045
U5117:U5145
C8885:C8900
Z8802:Z8803
R10131:R10284
H7895:H7898
G4514:G4549
S237:S238
I9787:I9996
H8195:H8197
W7672:W7673
J6973:J6974
S2017:S2018
E7322:E7323
AC2994:AC3001
G7024:G7026
K4763:K4764
J8080:J8084
S3293:S3306
O8255:O8256
AC2357:AC2363
Q7804:Q7805
F4971:F4982
J1837:J1850
H2333:H2356
F3044:F3045
V2378:V2385
Z3855:Z3861
N7674:N7675
F8493:F8514
X7595:X7615
A6857:A6859
O2431:O2437
W326:W348
K7324:K7328
X6502:X6589
K4404:K4411
V8232:V8233
I3645:I3703
A4890:A4935
R8052:R8075
K7823:K7824
X1528:X1585
E8168:E8171
AC8015:AC8033
W8515:W8521
M8126:M8136
V3046:V3092
B2019:B2022
AD373:AD381
C7890:C7891
G2386:G2417
F2062:F2075
U1381:U1403
I5334:I5349
A4017:A4026
I3490:I3502
AC1331:AC1339
AD8806:AD8820
F6039:F6041
AB2076:AB2079
K4983:K4991
X7820:X7822
N7875:N7876
D3776:D3779
U1759:U1762
G1603:G1615
Z2059:Z2061
K4570:K4584
Q6984:Q6986
W1225:W1229
Z825:Z828
J6275:J6424
R3352:R3359
L1470:L1471
X7618:X7626
F2546:F2642
A8860:A8876
Y7371:Y7387
F5932:F6034
A7973:A7975
W1766:W1767
J3810:J3825
T8103:T8125
K7998:K8001
AB4723:AB4737
E1669:E1675
U3503:U3539
AB8910:AB8919
B2047:B2051
S1894:S1897
Z1324:Z1325
R6042:R6045
O9299:O9367
B11201:B11264
B8885:B8900
V7888:V7889
B7840:B7841
Y8775:Y8776
A4004:A4016
N1586:N1599
F444:F451
AA230:AA231
M9380:M9448
V1744:V1754
H9787:H9996
G8195:G8197
V6430:V6435
AA5363:AA5364
Z1979:Z1987
G6995:G6996
L6929:L6930
I8940:I8952
D7301:D7302
K4967:K4970
F7024:F7026
K7893:K7894
J4478:J4507
N8255:N8256
Y3143:Y3174
AB2823:AB2827
S436:S439
K8015:K8033
E8515:E8521
AD5070:AD5078
P7804:P7805
B2984:B2993
C2023:C2025
P8179:P8185
Z8493:Z8514
G2333:G2356
Y3720:Y3732
M7911:M7915
D4508:D4513
F7924:F7927
U6436:U6501
Y2481:Y2510
F9784:F9786
Z2126:Z2202
F821:F824
M7953:M7954
J7324:J7328
N2052:N2054
B4444:B4450
C8751:C8758
AA7404:AA7430
Q8052:Q8075
B5079:B5093
M8591:M8614
S2366:S2377
AB8015:AB8033
F2047:F2051
AD1131:AD1135
A2019:A2022
F11201:F11264
P7333:P7337
AC373:AC381
F2386:F2417
D1262:D1264
AA1988:AA1995
K2721:K2776
AC8806:AC8820
J4723:J4737
AB9230:AB9298
F5466:F5784
Z8161:Z8163
W7820:W7822
P8768:P8769
M7875:M7876
K8174:K8178
C5099:C5101
U4822:U4829
C3776:C3779
F4830:F4831
T1759:T1762
F1603:F1615
AC9652:AC9783
D1744:D1754
W4349:W4353
U9999:U10130
I6275:I6424
AD3810:AD3825
K1470:K1471
E2546:E2642
A7329:A7330
T8762:T8765
Y2858:Y2928
Z5019:Z5069
B7880:B7881
B7833:B7836
I7773:I7774
AC3116:AC3124
J2055:J2058
A6803:A6815
V6861:V6862
R1894:R1897
F8689:F8696
AA2031:AA2032
H3843:H3854
D7640:D7641
Z7693:Z7768
A7840:A7841
S7885:S7886
I7011:I7012
S3790:S3794
AD8486:AD8487
E444:E451
R5366:R5367
T7770:T7771
AB3376:AB3382
T4832:T4834
H2126:H2202
I1650:I1661
A7935:A7937
W1141:W1142
K6929:K6930
L8225:L8226
H8940:H8952
W7322:W7323
C7301:C7302
N2261:N2332
W2023:W2025
AA3733:AA3757
J7893:J7894
F9161:F9229
H7823:H7824
S4086:S4132
O1322:O1323
L5402:L5444
X3720:X3732
AB7082:AB7083
H7061:H7062
L7911:L7915
AC9368:AC9374
E7924:E7927
AC7963:AC7964
F961:F962
U11139:U11200
AC1503:AC1508
E821:E824
L7953:L7954
V917:V923
A4444:A4450
Z7404:Z7430
H10585:H10633
AD2006:AD2009
J4835:J4867
AC4027:AC4036
A8282:A8283
W1283:W1284
Q386:Q413
B8954:B9022
D5094:D5098
T8535:T8564
J3568:J3575
E6920:E6921
A6216:A6274
R3826:R3833
J6907:J6912
E2678:E2687
M7868:M7871
T5377:T5385
AB8806:AB8820
Z8617:Z8622
AA9230:AA9298
M4763:M4764
L1931:L1955
G2471:G2480
P7810:P7812
J8174:J8178
M8168:M8171
O7845:O7848
S8179:S8185
J8036:J8039
B6922:B6923
C3106:C3108
C3309:C3351
I4017:I4026
L11279:L11281
X8904:X8908
P1640:P1648
Q8229:Q8230
Z3473:Z3489
M4585:M4587
A7880:A7881
N7941:N7942
A7833:A7836
W6436:W6501
H7773:H7774
Z7818:Z7819
AB3116:AB3124
H9784:H9786
Z2098:Z2100
A326:A348
U6861:U6862
A4086:A4132
C7640:C7641
Y7693:Y7768
R3790:R3794
U8772:U8773
T7956:T7957
Q5366:Q5367
AD3872:AD3875
V3110:V3115
K9368:K9374
P7402:P7403
AC5790:AC5824
O8591:O8614
U7849:U7852
E7431:E7432
W1320:W1321
K5334:K5349
AB1254:AB1255
Z580:Z583
H1650:H1661
W7085:W7086
C7899:C7903
S7595:S7615
T7433:T7459
AB8048:AB8051
AD8093:AD8102
E9161:E9229
AB8209:AB8210
U2702:U2707
G1340:G1374
R8778:R8794
J1131:J1135
AA7082:AA7083
D7924:D7927
U2675:U2676
A8186:A8189
AB5000:AB5018
AB1503:AB1508
R3560:R3567
K3036:K3041
AB2033:AB2035
Q1180:Q1181
G10585:G10633
G3761:G3775
P358:P359
I4835:I4867
B4412:B4413
AB4027:AB4036
L3540:L3547
I4414:I4442
I1247:I1248
V1283:V1284
A8954:A9022
W2062:W2075
L8004:L8008
X9449:X9651
U1662:U1667
AC2031:AC2032
D6920:D6921
H1477:H1498
L6984:L6986
B5932:B6034
I6907:I6912
G2929:G2983
F3930:F3939
S5377:S5385
Y8617:Y8622
AB8190:AB8194
J585:J587
L4763:L4764
W6430:W6435
A8089:A8092
Y1956:Y1962
N8768:N8769
C8772:C8773
Z2468:Z2470
H726:H727
X7333:X7337
C7849:C7852
E1756:E1758
T5234:T5288
AB4460:AB4477
A6922:A6923
J3758:J3760
E1015:E1016
M7343:M7369
K11279:K11281
E8625:E8671
X7400:X7401
P8229:P8230
I9023:I9091
D3621:D3635
O1640:O1648
R1997:R2003
B7433:B7459
V6436:V6501
AB3548:AB3552
Y7818:Y7819
G9784:G9786
J8209:J8210
O3188:O3193
G7893:G7894
W1099:W1101
D8751:D8758
S7956:S7957
H1131:H1135
U3110:U3115
C5079:C5093
A4820:A4821
F7388:F7399
AD5094:AD5098
AD2644:AD2674
H1921:H1930
AA1254:AA1255
H928:H950
V7920:V7923
AD8802:AD8803
X462:X465
X8215:X8216
Y2101:Y2125
AA8048:AA8051
S793:S819
W2017:W2018
T2702:T2707
Q7998:Q8001
F1340:F1374
H3605:H3620
B4696:B4722
H8585:H8586
C6816:C6820
R4992:R4999
R7890:R7891
W3293:W3306
AB1011:AB1014
C1662:C1667
Z3940:Z4003
S3636:S3644
T2675:T2676
P10651:P10666
R7674:R7675
J8190:J8194
N7277:N7279
B9092:B9160
C961:C962
M3862:M3871
L6425:L6428
F3761:F3775
S3307:S3308
AA4027:AA4036
K3238:K3252
S2431:S2437
AA1324:AA1325
K3540:K3547
AB6502:AB6589
H4414:H4442
A10286:A10441
G8174:G8178
U1853:U1882
I530:I562
W9449:W9651
AC1772:AC1775
AB2031:AB2032
AA8237:AA8238
AD1622:AD1638
G1477:G1498
M1329:M1330
F4550:F4569
T1017:T1019
N7904:N7906
F2929:F2983
E3930:E3939
J4588:J4598
Y1381:Y1403
J3548:J3552
I585:I587
X8227:X8228
D5324:D5333
A8354:A8355
K3002:K3035
D1967:D1977

In [11]:
df_copia = df.copy()
df_copia.head(5)

,No.,DEPARTAMENTO,MUNICIPIO,VEREDA,NOMBRE DEL VIVERO,LATITUD,LONGITUD,ALTITUD,ESTADO,NÚMERO DE REGISTRO OTORGADO,...,PROPIETARIO NOMBRE,NO. CEDULA DEL PROPIETARIO,TELÉFONO DEL PROPIETARIO,DIRECCIÓN DEL PROPIETARIO,CORREO ELECTRÓNICO,NOMBRE DEL ASISTENTE TÉCNICO,CÉDULA DEL ASISTENTE TÉCNICO,TARJETA PROFESIONAL DEL ASISTENTE TÉCNICO,TELÉFONO DEL ASISTENTE TÉCNICO,OBSERVACIONES
0,1,AMAZONAS,LETICIA,SECTOR NAZARETH,VIVERO GRANJA NAZARETH,-4.106478,-70.037956,71,REGISTRADO,910010001,...,OSCAR ENRIQUE SÁNCHEZ GUERRERO,"15,879,024",3187912285,CALLE 11 # 12-98 BARRIO VICTORIA REGIA,agricultura@amazonas.gov.co,MAYRA ALEJANDRA ROJAS VARON,1110518462,161016-0568965 TLM,3113448291,NaN
1,1,ANTIOQUIA,Jerico,La Estrella,San Basilio S.A.S,5.758195,-75.768022,2800,Registrado,92950,...,Duban Alberto Ruiz Ospina,70730011,3155750451,Calle cuarta # 2-25 Barrio San Vivente Jericó,gerencia@productorasanbasilio.com; asistenciat...,Edilma Betancurt Ruiz,24791263,66209436973RIS,3105187628,NaN
2,2,ANTIOQUIA,Jerico,El Balcon Sector La Leona,El Balcon,5.809731,-75.765759,1900,Registrado,92948,...,Jose Maria Prieto Villegas,71591849,3128512959,Carrera 76 # 34a-41 Oficina 102 Edificio Camburo,josemariaprieto@gmail.com,Catalina Maria Zuluaga Amaya,43873262,,,NaN
3,3,ANTIOQUIA,Entrerrios,El Zancudo - paraje La Tabla- Via San Pedro - ...,Agricolas y Vivero Guacamayas,6.561369,-75.537789,2502,Registrado,92946,...,Juan Camilo Ruiz Perez,15315744,3104363299,Calle9# 31 - 105 El Poblado,juancamilorp@gmail.com,Lina Marcela Morales Herrera,1040037431,53639,3213988643,NaN
4,4,ANTIOQUIA,Urrao,San Jose - Via Urrao - Betulia Km 7,Plantuladora El Paraiso,6.259529,-76.129879,1876,Registrado,22666,...,Julian Andres Bulla,1055670236,3124521042,Marinilla - Cra 44-B #2915 Conjunto Bariloche,"plantulasparaiso3@hotmail,com",Diego Armando Solano Montenegro,74282972,23935,3104932787,NaN

In [12]:
for rango in hoja.merged_cells.ranges:
    if rango.min_col == rango.max_col:
        columna = rango.min_col - 1
        fila_inicio = rango.min_row -2
        fila_fin = rango.max_row -1

        if fila_inicio < 0 < fila_fin > len(df_copia):
            continue
        valor = hoja.cell(row=rango.min_row, column=rango.min_col).value

        df_copia.iloc[fila_inicio:fila_fin, columna] = valor

In [13]:
df_copia.to_excel("relleno.xlsx",index=False)

In [14]:
df_copia.isna().sum()

No.                                              7
DEPARTAMENTO                                     5
MUNICIPIO                                       34
VEREDA                                         379
NOMBRE DEL VIVERO                              159
LATITUD                                        672
LONGITUD                                       672
ALTITUD                                       1329
ESTADO                                          23
NÚMERO DE REGISTRO OTORGADO                    179
FECHA DE OTORGAMIENTO DE REGISTRO              152
VIGENCIA                                       270
CAPACIDAD DE PRODUCCIÓN plantas/año           4936
FRUTALES                                      7211
CITRICOS                                      7623
FORESTALES                                    6342
ORNAMENTALES                                  3207
HORTALIZAS                                    8230
AROMATICAS Y MEDICINALES                      8203
OTRAS ESPECIES                                7166
PROPIETARIO NOMBRE                             464
NO. CEDULA DEL PROPIETARIO                     256
TELÉFONO DEL PROPIETARIO                       271
DIRECCIÓN DEL PROPIETARIO                     3079
CORREO ELECTRÓNICO                             520
NOMBRE DEL ASISTENTE TÉCNICO                  1902
CÉDULA  DEL ASISTENTE TÉCNICO                 2019
TARJETA PROFESIONAL  DEL ASISTENTE TÉCNICO    2052
TELÉFONO DEL ASISTENTE TÉCNICO                4250
OBSERVACIONES                                 6188
dtype: int64

In [15]:
df_copia.isna().all(axis=1).sum()

np.int64(1)

In [16]:
df_copia.shape

(11295, 30)

In [17]:
df_copia= df_copia.dropna(how='all')
#df_copia.dropna(how='any')

In [18]:
df_copia.shape

(11294, 30)

In [19]:
df_copia.to_excel("sin_vacios.xlsx",index=False)

In [20]:
n = 5
(df_copia.notna().sum(axis=1) <=n).sum()

np.int64(6)

In [21]:
df_copia[df_copia.notna().sum(axis=1) <=n]

,No.,DEPARTAMENTO,MUNICIPIO,VEREDA,NOMBRE DEL VIVERO,LATITUD,LONGITUD,ALTITUD,ESTADO,NÚMERO DE REGISTRO OTORGADO,...,PROPIETARIO NOMBRE,NO. CEDULA DEL PROPIETARIO,TELÉFONO DEL PROPIETARIO,DIRECCIÓN DEL PROPIETARIO,CORREO ELECTRÓNICO,NOMBRE DEL ASISTENTE TÉCNICO,CÉDULA DEL ASISTENTE TÉCNICO,TARJETA PROFESIONAL DEL ASISTENTE TÉCNICO,TELÉFONO DEL ASISTENTE TÉCNICO,OBSERVACIONES
274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Cartagena “Guillermo Piñeres”,NaN,NaN,NaN,NaN,NaN,NaN
280,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
620,187,BOYACÁ,Villa de leyva,El Roble,Vivero el Roble,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3107,251,CUNDINAMARCA,FUSAGASUGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7584,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7585,89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df_copia[df_copia.notna().sum(axis=1) <=n].shape

(6, 30)

In [23]:
df_copia = df_copia[df_copia.notna().sum(axis=1) > n].copy()
df_copia

,No.,DEPARTAMENTO,MUNICIPIO,VEREDA,NOMBRE DEL VIVERO,LATITUD,LONGITUD,ALTITUD,ESTADO,NÚMERO DE REGISTRO OTORGADO,...,PROPIETARIO NOMBRE,NO. CEDULA DEL PROPIETARIO,TELÉFONO DEL PROPIETARIO,DIRECCIÓN DEL PROPIETARIO,CORREO ELECTRÓNICO,NOMBRE DEL ASISTENTE TÉCNICO,CÉDULA DEL ASISTENTE TÉCNICO,TARJETA PROFESIONAL DEL ASISTENTE TÉCNICO,TELÉFONO DEL ASISTENTE TÉCNICO,OBSERVACIONES
0,1,AMAZONAS,LETICIA,SECTOR NAZARETH,VIVERO GRANJA NAZARETH,-4.106478,-70.037956,71,REGISTRADO,910010001,...,OSCAR ENRIQUE SÁNCHEZ GUERRERO,"15,879,024",3187912285,CALLE 11 # 12-98 BARRIO VICTORIA REGIA,agricultura@amazonas.gov.co,MAYRA ALEJANDRA ROJAS VARON,1110518462,161016-0568965 TLM,3113448291,NaN
1,1,ANTIOQUIA,Jerico,La Estrella,San Basilio S.A.S,5.758195,-75.768022,2800,Registrado,92950,...,Duban Alberto Ruiz Ospina,70730011,3155750451,Calle cuarta # 2-25 Barrio San Vivente Jericó,gerencia@productorasanbasilio.com; asistenciat...,Edilma Betancurt Ruiz,24791263,66209436973RIS,3105187628,NaN
2,2,ANTIOQUIA,Jerico,El Balcon Sector La Leona,El Balcon,5.809731,-75.765759,1900,Registrado,92948,...,Jose Maria Prieto Villegas,71591849,3128512959,Carrera 76 # 34a-41 Oficina 102 Edificio Camburo,josemariaprieto@gmail.com,Catalina Maria Zuluaga Amaya,43873262,,,NaN
3,3,ANTIOQUIA,Entrerrios,El Zancudo - paraje La Tabla- Via San Pedro - ...,Agricolas y Vivero Guacamayas,6.561369,-75.537789,2502,Registrado,92946,...,Juan Camilo Ruiz Perez,15315744,3104363299,Calle9# 31 - 105 El Poblado,juancamilorp@gmail.com,Lina Marcela Morales Herrera,1040037431,53639,3213988643,NaN
4,4,ANTIOQUIA,Urrao,San Jose - Via Urrao - Betulia Km 7,Plantuladora El Paraiso,6.259529,-76.129879,1876,Registrado,22666,...,Julian Andres Bulla,1055670236,3124521042,Marinilla - Cra 44-B #2915 Conjunto Bariloche,"plantulasparaiso3@hotmail,com",Diego Armando Solano Montenegro,74282972,23935,3104932787,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11290,20,Vichada,Santa Rosalía,Flor Amarillo,Burití,4.56284,-70.295577,169,REGISTRADO,7187,...,JAMES JAIR AROS COLINA,1125550700,3204132505,Inspección de San Teodoro,jamesjair@hotmail.com,Daniel Arturo Rey Beltran,1121915298,25209-406012,3118507075,En el item otras especies se especifican espe...
11291,21,Vichada,Puerto Carreño,La esmeralda,Las maravillas,5.98872,-68.03826,76,REGISTRADO,6576,...,JOAQUIN UMAÑA ZARATE,79159978,3103104881,"Transversal 14-14-18, puerto carreño",gerardo.guzmanf1@gmail.com,Heiyer Niffer Acosta Acosta,93413033,21745,NaN,NaN
11292,22,Vichada,Puerto Carreño,Vereda el juriepe,Sembrando Futuro,6249370,-67746754,54,REGISTARDO,99001-23,...,IVAN GONZALEZ RODRIGUEZ,1127384354,3185978468,Calle 25 Barrio El estadio,isalili1503@hotmail.com,Daniel Arturo Rey Beltran,1121915298,25209-406012,NaN,NaN
11293,23,Vichada,La Primavera,Nueva ANTIOQUIA,Plantacón Cimarron,0.593896,"-69,2356.",93,REGISTRADO,9001-24,...,Prestige Colombia S.A.S,79878972,3185146449,Calle 40 No 32-50 oficina 403,lucia.torres@prestigecol.com,Lucia Torres Yanguma,20911319,25209-374852 CND,3158643305,NaN
11294,24,Vichada,Puerto Carreño,La esmeralda,LAS BONITAS,574081,-6822453,99,REGISTRADO,9001-25,...,Inversiones forestales de Colombia S.A.S,900151686-7,3165376732,calle 26 sur N° 22-27 casa santa ana envigado-...,natalia.quevedo@inverbosques.com,Gabriel Jaime Lopera Arango,15513574,19754,NaN,NaN

In [24]:
df_copia.shape

(11288, 30)

In [25]:
df_copia.to_excel("sin_imcompletos.xlsx",index=False)

##Ver Duplicados

In [26]:
## Ver duplicados
df_copia.duplicated().sum()

np.int64(63)

In [28]:
print(df_copia.duplicated().sum())
duplicados = df_copia[df_copia.duplicated(keep=False)]
duplicados

63

,No.,DEPARTAMENTO,MUNICIPIO,VEREDA,NOMBRE DEL VIVERO,LATITUD,LONGITUD,ALTITUD,ESTADO,NÚMERO DE REGISTRO OTORGADO,...,PROPIETARIO NOMBRE,NO. CEDULA DEL PROPIETARIO,TELÉFONO DEL PROPIETARIO,DIRECCIÓN DEL PROPIETARIO,CORREO ELECTRÓNICO,NOMBRE DEL ASISTENTE TÉCNICO,CÉDULA DEL ASISTENTE TÉCNICO,TARJETA PROFESIONAL DEL ASISTENTE TÉCNICO,TELÉFONO DEL ASISTENTE TÉCNICO,OBSERVACIONES
580,150,SANTANDER,Charalá,Vereda Virolín,Vivero Virolín,6.662384,-73.1152,1740,Registro Reciente,14657,...,César Orlando Gonzáles Borrero,11191849107,3115849102,vereda Quebrada de becerras(Duitama,cgonzalezborrero@gmail.com,César Orlando González Borrero,11191849107,15209-411494,3115849101,None
581,150,SANTANDER,Charalá,Vereda Virolín,Vivero Virolín,6.662384,-73.1152,1740,Registro Reciente,14657,...,César Orlando Gonzáles Borrero,11191849107,3115849102,vereda Quebrada de becerras(Duitama,cgonzalezborrero@gmail.com,César Orlando González Borrero,11191849107,15209-411494,3115849101,None
583,152,BOYACÁ,SOTAQUIRÁ,Vereda Carreño,Vivero La Reina,5.750232,-73.190214,2000,Registro Reciente,None,...,Omar Orlando Mondragon Peña,10709544899,3124645252,Vereda Carreño,omarsantomondra1988@gmail.com,Lisys Pedro Molano Gonzales,1052400607,15209-438030,3016837147,None
585,152,BOYACÁ,SOTAQUIRÁ,Vereda Carreño,Vivero La Reina,5.750232,-73.190214,2000,Registro Reciente,None,...,Omar Orlando Mondragon Peña,10709544899,3124645252,Vereda Carreño,omarsantomondra1988@gmail.com,Lisys Pedro Molano Gonzales,1052400607,15209-438030,3016837147,None
1281,32,CUNDINAMARCA,ANAPOIMA,"VEREDA SANTA ROSA,PREDIO LA ESMERALDA",SOSA CASTRO,None,None,None,REGISTRADO,250350170,...,JOSÉ VICENTE SOSA CASTRO,11450100,3123058473,"VEREDA EL PALMAR, PREDIO CASALOMA",vicentesosa057@gmail.com.,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10808,141,VALLE DEL CAUCA,LA CUMBRE,NaN,VIVERO THE EMOCIONES VERDES,3.816302,-76.62172,1147,REGISTRADO,76377-0430,...,JAMES NARVAEZ,1114487901,3184315339,None,emocionesverdescol@gmail.com,JAIRO RENE MORA,"13,013,762",76209-217803VLL,3183010666,None
10889,143,VALLE DEL CAUCA,CALI,CALLE 4 OESTE # 1 - 45,VIVERO SANTA RITA,3.4508,-76.54351,1018,REGISTRADO,76001-0432,...,CARLOS ALBERTO VERGARA GALVIS,15905369,3177043079,CALLE 4 OESTE # 1 - 45,viverosantaritacali@gmail.com,MAYRA ALEJANDRA GASCA VILLA,1114817051,76209-265068 VLL,3137773496,None
10890,143,VALLE DEL CAUCA,CALI,CALLE 4 OESTE # 1 - 45,VIVERO SANTA RITA,3.4508,-76.54351,1018,REGISTRADO,76001-0432,...,CARLOS ALBERTO VERGARA GALVIS,15905369,3177043079,CALLE 4 OESTE # 1 - 45,viverosantaritacali@gmail.com,MAYRA ALEJANDRA GASCA VILLA,1114817051,76209-265068 VLL,3137773496,None
11094,145,VALLE DEL CAUCA,ROLDANILLO,VIA PANORAMA KM 1 VIA BOLIVAR VEREDA EL HOBO,VIVERO Y ARTESANIAS ROLDANILLO,4.447147,-76.1368,1009,REGISTRADO,76622-0434,...,JORGE TULIO TAMAYO,6457761,3113018489,VIA PANORAMA KM 1 VIA BOLIVAR VEREDA EL HOBO,viveroroldanillo@gmail.com,LUIS ERNESTO HURTADO,6558265,T.P 9242,None,None
11102,145,VALLE DEL CAUCA,ROLDANILLO,VIA PANORAMA KM 1 VIA BOLIVAR VEREDA EL HOBO,VIVERO Y ARTESANIAS ROLDANILLO,4.447147,-76.1368,1009,REGISTRADO,76622-0434,...,JORGE TULIO TAMAYO,6457761,3113018489,VIA PANORAMA KM 1 VIA BOLIVAR VEREDA EL HOBO,viveroroldanillo@gmail.com,LUIS ERNESTO HURTADO,6558265,T.P 9242,None,None

In [29]:
df_copia = df_copia.drop_duplicates()

In [30]:
df_copia.shape

(11225, 30)

In [31]:
df_copia.to_excel("sin_duplicados.xlsx",index=False)

In [32]:
df_copia.info()

<class 'pandas.DataFrame'>
Index: 11225 entries, 0 to 11294
Data columns (total 30 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   No.                                         11220 non-null  object
 1   DEPARTAMENTO                                11225 non-null  str
 2   MUNICIPIO                                   11196 non-null  str
 3   VEREDA                                      10889 non-null  str
 4   NOMBRE DEL VIVERO                           11072 non-null  str
 5   LATITUD                                     10561 non-null  object
 6   LONGITUD                                    10561 non-null  object
 7   ALTITUD                                     9904 non-null   object
 8   ESTADO                                      11209 non-null  str
 9   NÚMERO DE REGISTRO OTORGADO                 11054 non-null  object
 10  FECHA DE OTORGAMIENTO DE REGISTRO           11081 non-null  object
 11  VIGENCIA                                    10962 non-null  object
 12  CAPACIDAD DE PRODUCCIÓN plantas/año         6336 non-null   object
 13  FRUTALES                                    4078 non-null   object
 14  CITRICOS                                    3672 non-null   object
 15  FORESTALES                                  4940 non-null   object
 16  ORNAMENTALES                                8036 non-null   object
 17  HORTALIZAS                                  3065 non-null   object
 18  AROMATICAS Y MEDICINALES                    3092 non-null   object
 19  OTRAS ESPECIES                              4126 non-null   object
 20  PROPIETARIO NOMBRE                          10768 non-null  str
 21  NO. CEDULA DEL PROPIETARIO                  10976 non-null  object
 22  TELÉFONO DEL PROPIETARIO                    10961 non-null  object
 23  DIRECCIÓN DEL PROPIETARIO                   8189 non-null   object
 24  CORREO ELECTRÓNICO                          10712 non-null  object
 25  NOMBRE DEL ASISTENTE TÉCNICO                9335 non-null   object
 26  CÉDULA  DEL ASISTENTE TÉCNICO               9218 non-null   object
 27  TARJETA PROFESIONAL  DEL ASISTENTE TÉCNICO  9185 non-null   object
 28  TELÉFONO DEL ASISTENTE TÉCNICO              6991 non-null   object
 29  OBSERVACIONES                               5094 non-null   object
dtypes: object(24), str(6)
memory usage: 2.7+ MB

In [34]:
df_copia["ESTADO "].unique()

<StringArray>
[                                              'REGISTRADO',
                                              'Registrado ',
                                               'Registrado',
                                              ' Registrado',
                                                 'Moficado',
                                              'REGISTRADO ',
                                                        nan,
                                               'REGISTRADA',
                                             'REGISTRADO  ',
                                       'Registro Cancelado',
                                               'Modificado',
                                    'REGISTRADO MODIFICADO',
                                               'Suspendido',
                                       'Registro Reciente ',
                                      'Registro Modificado',
                                               'En tramite',
                                              'Actualizado',
                                               'Registrada',
                                      'En trámite registro',
                                             'Sin Registro',
                                          'Sin Información',
                                                'CANCELADO',
                                                'NO RENOVO',
                                            'NO REGISTRADO',
                          'REGISTRADO                     ',
 'REGISTRADO                                              ',
                                             '  REGISTRADO',
                                             'MODIFICACIÓN',
                                                 'REGISTRO',
                                                 'REGSITRO',
                                                   'ACTIVO',
                                              'REGISTRAODO',
                       'RESOLUCION 00029168 DEL 14-11-2025',
                                               'REGSITRADO',
                        '(Cancelado Citricos )  REGISTRADO',
                                     'CANCELADO (Citricos)',
          'REGISTRADO (Frutales, ornamentales, hortalizas)',
                                               'REGISTARDO']
Length: 38, dtype: str

In [35]:
df_copia["ESTADO "].value_counts(dropna=False)

ESTADO
REGISTRADO                                                  8270
REGISTRO                                                    1262
ACTIVO                                                       532
MODIFICACIÓN                                                 366
REGISTRADO                                                   270
Registrado                                                   232
NO REGISTRADO                                                 98
REGISTRADA                                                    48
REGSITRO                                                      37
NaN                                                           16
Registrada                                                    16
Registrado                                                    15
NO RENOVO                                                     14
Registro Reciente                                             10
CANCELADO                                                      6
  REGISTRADO                                                   4
(Cancelado Citricos )  REGISTRADO                              4
Registro Cancelado                                             2
Modificado                                                     2
REGISTRADO MODIFICADO                                          2
Actualizado                                                    2
 Registrado                                                    1
Moficado                                                       1
REGISTRADO                                                     1
Suspendido                                                     1
Registro Modificado                                            1
En tramite                                                     1
En trámite registro                                            1
Sin Registro                                                   1
Sin Información                                                1
REGISTRADO                                                     1
REGISTRADO                                                     1
REGISTRAODO                                                    1
RESOLUCION 00029168 DEL 14-11-2025                             1
REGSITRADO                                                     1
CANCELADO (Citricos)                                           1
REGISTRADO (Frutales, ornamentales, hortalizas)                1
REGISTARDO                                                     1
Name: count, dtype: int64

In [36]:
df_copia["ESTADO "] = df_copia["ESTADO "].astype("string").str.strip().str.upper()

In [37]:
df_copia["ESTADO "].value_counts(dropna=False)

ESTADO
REGISTRADO                                         8795
REGISTRO                                           1262
ACTIVO                                              532
MODIFICACIÓN                                        366
NO REGISTRADO                                        98
REGISTRADA                                           64
REGSITRO                                             37
<NA>                                                 16
NO RENOVO                                            14
REGISTRO RECIENTE                                    10
CANCELADO                                             6
(CANCELADO CITRICOS )  REGISTRADO                     4
REGISTRO CANCELADO                                    2
MODIFICADO                                            2
REGISTRADO MODIFICADO                                 2
ACTUALIZADO                                           2
MOFICADO                                              1
SUSPENDIDO                                            1
REGISTRO MODIFICADO                                   1
EN TRAMITE                                            1
EN TRÁMITE REGISTRO                                   1
SIN REGISTRO                                          1
SIN INFORMACIÓN                                       1
REGISTRAODO                                           1
RESOLUCION 00029168 DEL 14-11-2025                    1
REGSITRADO                                            1
CANCELADO (CITRICOS)                                  1
REGISTRADO (FRUTALES, ORNAMENTALES, HORTALIZAS)       1
REGISTARDO                                            1
Name: count, dtype: Int64

In [38]:
df_copia["ESTADO "] = df_copia["ESTADO "].replace(
    {
        "MOFICADO": "MODIFICADO",
        "REGISTRADA": "REGISTRADO",
        "REGSITRO": "REGISTRO",
        "REGSITRADO": "REGISTRADO",
        "REGISTRAODO": "RESGSITRADO",
    }
)

In [ ]:
tus

In [39]:
df_copia["ESTADO "].unique()
df_copia["ESTADO "].value_counts(dropna=False)g s

ESTADO
REGISTRADO                                         8860
REGISTRO                                           1299
ACTIVO                                              532
MODIFICACIÓN                                        366
NO REGISTRADO                                        98
<NA>                                                 16
NO RENOVO                                            14
REGISTRO RECIENTE                                    10
CANCELADO                                             6
(CANCELADO CITRICOS )  REGISTRADO                     4
MODIFICADO                                            3
REGISTRO CANCELADO                                    2
REGISTRADO MODIFICADO                                 2
ACTUALIZADO                                           2
SUSPENDIDO                                            1
REGISTRO MODIFICADO                                   1
EN TRAMITE                                            1
EN TRÁMITE REGISTRO                                   1
SIN REGISTRO                                          1
SIN INFORMACIÓN                                       1
RESGSITRADO                                           1
RESOLUCION 00029168 DEL 14-11-2025                    1
CANCELADO (CITRICOS)                                  1
REGISTRADO (FRUTALES, ORNAMENTALES, HORTALIZAS)       1
REGISTARDO                                            1
Name: count, dtype: Int64